//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraSuaVl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BubleTea
    {
        [Display (Name = "Mã Số")]
        public int id { get; set; }
        [Display (Name= "Tên Sản Phẩm")]
        public string Name { get; set; }
        [Display (Name = "Giá")]
        public int Price { get; set; }
        [Display (Name = "Món Thêm")]
        public string Topping { get; set; }
    }
}
